package com.mycompany.assignment3;

import java.io.Serializable;

import java.util.Random;

public class PolicyException extends Exception implements Serializable{
    
    private int ID;
    
    public PolicyException(int ID){
        
        this.ID = ID;
        this.ID = generateID();
        
    }
    
    public int generateID(){
        
        //Random random = new Random();
        //int id = (int) 3000000 + random.nextInt(100000);
        int id = (int) ((Math.random() * ((3999999 - 3000000) + 1)) + 3000000);
        return id;
        
    }
    
    public String toString(){
        
        return "The Policy ID was not valid and a new ID (" + ID + ") is generated by admin and assigned for the policy";
        
    }

    public int getID(){return ID;}
    
    public void setID(int ID){this.ID = ID;}
    
}
