/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment3;

import javax.swing.*;
/**
 *
 * @author User
 */
public class UpdateUI extends javax.swing.JFrame {

    /**
     * Creates new form UpdateUI
     */
    
    static InsurancePolicy ip;
    static UserUI userUI;
    
    public UpdateUI(InsurancePolicy ip, UserUI UI) {
        
        UpdateUI.ip = ip;
        userUI = UI;
        initComponents();
        fillTextFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        tppButton = new javax.swing.JRadioButton();
        cpButton = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        polText1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        polID1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmText1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        myText1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        pText1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ctCombo1 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        nocText1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        yText = new javax.swing.JTextField();
        commLabel = new javax.swing.JLabel();
        cText = new javax.swing.JTextField();
        lvlLabel = new javax.swing.JLabel();
        lvlText = new javax.swing.JTextField();
        updateText = new javax.swing.JButton();
        clearText = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tppButton.setSelected(true);
        tppButton.setText("Third Party Policy");
        tppButton.setEnabled(false);
        tppButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tppButtonStateChanged(evt);
            }
        });

        cpButton.setText("Comprehensive Policy");
        cpButton.setEnabled(false);

        jLabel19.setText("Policy Holder Name");

        jLabel20.setText("Policy ID");

        polID1.setEnabled(false);

        jLabel21.setText("Enter Car Details");

        jLabel22.setText("Car Model");

        jLabel23.setText("Manufacturing Year");

        jLabel24.setText("Price");

        jLabel25.setText("Car Type");

        ctCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Number of Claims");

        jLabel27.setText("Enter Expiry Date");

        jLabel10.setText("Day");

        jLabel11.setText("Month");

        jLabel12.setText("Year");

        commLabel.setText("Comment");

        lvlLabel.setText("Level");

        updateText.setText("Update");
        updateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTextActionPerformed(evt);
            }
        });

        clearText.setText("Clear");
        clearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commLabel)
                            .addComponent(lvlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pText1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myText1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmText1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polID1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polText1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(ctCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nocText1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tppButton)
                        .addGap(184, 184, 184)
                        .addComponent(cpButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(updateText, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dText, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(mText)
                            .addComponent(yText)
                            .addComponent(cText)
                            .addComponent(lvlText)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(clearText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1795, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tppButton)
                    .addComponent(cpButton))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(polText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(polID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(myText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(pText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ctCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(nocText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(yText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commLabel)
                    .addComponent(cText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlLabel)
                    .addComponent(lvlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateText)
                    .addComponent(clearText))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tppButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tppButtonStateChanged
        // TODO add your handling code here:
        if(tppButton.isSelected()){

            lvlLabel.setVisible(false);
            lvlText.setVisible(false);
            commLabel.setText("Comment");

        }else{

            commLabel.setText("Driver Age");
            lvlLabel.setVisible(true);
            lvlText.setVisible(true);

        }
    }//GEN-LAST:event_tppButtonStateChanged

    private void updateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTextActionPerformed
        // TODO add your handling code here:
        try{

            String policyHoldName = polText1.getText();
            int policyID = Integer.parseInt(polID1.getText());
            String carModel = cmText1.getText();
            int manufacturingYear = Integer.parseInt(myText1.getText());
            double price = Double.parseDouble(pText1.getText());
            CarType carType = CarType.valueOf(ctCombo1.getSelectedItem().toString().toUpperCase());
            Car newCar = new Car(carModel, manufacturingYear, price, carType);
            int numberOfClaims = Integer.parseInt(nocText1.getText());
            int day = Integer.parseInt(dText.getText());
            int month = Integer.parseInt(mText.getText());
            int year = Integer.parseInt(yText.getText());
            MyDate newDate = new MyDate(year, month, day);
            ip.setPolicyHolderName(policyHoldName);
            ip.setID(policyID);
            ip.setCar(newCar);
            ip.setNumberOfClaims(numberOfClaims);
            ip.setExpiryDate(newDate);

            if(tppButton.isSelected()){

                String comment = cText.getText();
                ((ThirdPartyPolicy)ip).comments = comment;

            }else{

                int driverAge1 = Integer.parseInt(cText.getText());
                int level1 = Integer.parseInt(lvlText.getText());
                ((ComprehensivePolicy)ip).driverAge = driverAge1;
                ((ComprehensivePolicy)ip).level = level1;

            }

            JOptionPane.showMessageDialog(this, "Policy has been updated!");
            userUI.fillTable();
            this.dispose();

        }

        catch(Exception e){

            JOptionPane.showMessageDialog(this, "A field may be empty or you have entered a string where it asks for an integer!");

        }

    }//GEN-LAST:event_updateTextActionPerformed

    private void clearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextActionPerformed
        // TODO add your handling code here:
        polText1.setText("");
        polID1.setText("");
        cmText1.setText("");
        myText1.setText("");
        pText1.setText("");
        nocText1.setText("");
        dText.setText("");
        mText.setText("");
        yText.setText("");
        cText.setText("");
        lvlText.setText("");
    }//GEN-LAST:event_clearTextActionPerformed

    public void fillTextFields(){
        
        polText1.setText(ip.getPolicyHolderName());
        polID1.setText(ip.getID() + "");
        cmText1.setText(ip.getCar().getModel());
        myText1.setText(ip.getCar().getManufacturingYear() + "");
        pText1.setText(ip.getCar().getPrice() + "");
        
        CarType[] carTypes = CarType.values();
        ctCombo1.removeAllItems();
        for(CarType ct: carTypes){
                
            ctCombo1.addItem(ct.toString().toUpperCase());
                
        }
        
        ctCombo1.setSelectedItem(ip.car.getType());
        nocText1.setText(ip.getNumberOfClaims() + "");
        dText.setText(ip.getExpiryDate().getDay() + "");
        mText.setText(ip.getExpiryDate().getMonth() + "");
        yText.setText(ip.getExpiryDate().getYear() + "");
        
        if(ip instanceof ThirdPartyPolicy){
            
            tppButton.setSelected(true);
            cpButton.setSelected(false);
            cText.setText(((ThirdPartyPolicy)ip).comments);
            lvlLabel.setVisible(false);
            lvlText.setVisible(false);
            
        }else{
            
            tppButton.setSelected(false);
            cpButton.setSelected(true);
            commLabel.setText("Driver Age");
            cText.setText(((ComprehensivePolicy)ip).driverAge + "");
            lvlText.setText(((ComprehensivePolicy)ip).level + "");
            lvlLabel.setVisible(true);
            lvlText.setVisible(true);
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main_UPdate(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UpdateUI(ip, userUI).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cText;
    private javax.swing.JButton clearText;
    private javax.swing.JTextField cmText1;
    private javax.swing.JLabel commLabel;
    private javax.swing.JRadioButton cpButton;
    private javax.swing.JComboBox<String> ctCombo1;
    private javax.swing.JTextField dText;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JTextField lvlText;
    private javax.swing.JTextField mText;
    private javax.swing.JTextField myText1;
    private javax.swing.JTextField nocText1;
    private javax.swing.JTextField pText1;
    private javax.swing.JTextField polID1;
    private javax.swing.JTextField polText1;
    private javax.swing.JRadioButton tppButton;
    private javax.swing.JButton updateText;
    private javax.swing.JTextField yText;
    // End of variables declaration//GEN-END:variables
}
