/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment3;

import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
/**
 *
 * @author User
 */
public class UserUI extends javax.swing.JFrame {

    static ArrayList<String> cities;
    static User user;
    static Login login;
    
    /**
     * Creates new form UserUI
     * @param user
     * @param login
     * @param cities
     */
    public UserUI(User user, Login login, ArrayList<String> cities) {
        UserUI.user = user;
        UserUI.login = login;
        UserUI.cities = cities;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        policyTablePopUp = new javax.swing.JPopupMenu();
        DeletefromPopUp = new javax.swing.JMenuItem();
        UpdatefromPopUp = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        streetNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        streetText = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        suburbText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cityCombo = new javax.swing.JComboBox<>();
        cityText = new javax.swing.JTextField();
        cityChoice = new javax.swing.JCheckBox();
        changeData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        tppButton = new javax.swing.JRadioButton();
        cpButton = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        polText1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        polID1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmText1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        myText1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        pText1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ctCombo1 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        nocText1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        yText = new javax.swing.JTextField();
        commLabel = new javax.swing.JLabel();
        cText = new javax.swing.JTextField();
        lvlLabel = new javax.swing.JLabel();
        lvlText = new javax.swing.JTextField();
        addPolText = new javax.swing.JButton();
        clearText = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        findPolicyText = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        policyArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        policyTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        policyTable1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        cmFilter = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        epFilter = new javax.swing.JTextField();
        filterBDbutton = new javax.swing.JButton();
        sort = new javax.swing.JCheckBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        LogoutOption = new javax.swing.JMenu();

        policyTablePopUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                policyTablePopUpMousePressed(evt);
            }
        });

        DeletefromPopUp.setText("Delete");
        DeletefromPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletefromPopUpActionPerformed(evt);
            }
        });
        policyTablePopUp.add(DeletefromPopUp);

        UpdatefromPopUp.setText("Update");
        UpdatefromPopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatefromPopUpActionPerformed(evt);
            }
        });
        policyTablePopUp.add(UpdatefromPopUp);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jLabel1.setText("User ID");

        idText.setEnabled(false);

        jLabel2.setText("Name");

        jLabel3.setText("Username");

        usernameText.setEnabled(false);

        jLabel4.setText("Password");

        jLabel5.setText("Address Information");

        jLabel6.setText("Street Number");

        jLabel7.setText("Street Name");

        jLabel8.setText("Suburb");

        jLabel9.setText("City");

        cityCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cityText.setEnabled(false);

        cityChoice.setText("New City");
        cityChoice.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityChoiceItemStateChanged(evt);
            }
        });

        changeData.setText("Edit");
        changeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idText)
                            .addComponent(nameText)
                            .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(passText)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(streetNum)
                                .addComponent(streetText)
                                .addComponent(suburbText, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(changeData, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1779, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(streetNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(streetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(suburbText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cityCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityChoice))
                .addGap(35, 35, 35)
                .addComponent(changeData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Edit Personal Data", jPanel1);

        buttonGroup1.add(tppButton);
        tppButton.setSelected(true);
        tppButton.setText("Third Party Policy");
        tppButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tppButtonStateChanged(evt);
            }
        });

        buttonGroup1.add(cpButton);
        cpButton.setText("Comprehensive Policy");

        jLabel19.setText("Policy Holder Name");

        jLabel20.setText("Policy ID");

        jLabel21.setText("Enter Car Details");

        jLabel22.setText("Car Model");

        jLabel23.setText("Manufacturing Year");

        jLabel24.setText("Price");

        jLabel25.setText("Car Type");

        ctCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Number of Claims");

        jLabel27.setText("Enter Expiry Date");

        jLabel10.setText("Day");

        jLabel11.setText("Month");

        jLabel12.setText("Year");

        commLabel.setText("Comment");

        lvlLabel.setText("Level");

        addPolText.setText("Add Policy");
        addPolText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPolTextActionPerformed(evt);
            }
        });

        clearText.setText("Clear");
        clearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commLabel)
                            .addComponent(lvlLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pText1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(myText1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmText1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polID1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polText1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(ctCombo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nocText1)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel27))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tppButton)
                        .addGap(214, 214, 214)
                        .addComponent(cpButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(addPolText)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dText, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(mText)
                                    .addComponent(yText)
                                    .addComponent(cText)
                                    .addComponent(lvlText)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(clearText, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1765, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tppButton)
                    .addComponent(cpButton))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(polText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(polID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cmText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(myText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(pText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(ctCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(nocText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(yText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commLabel)
                    .addComponent(cText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvlLabel)
                    .addComponent(lvlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPolText)
                    .addComponent(clearText))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jTabbedPane1.addTab("Add Policy", jScrollPane1);

        jLabel13.setText("Policy ID");

        findButton.setText("FIND");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        policyArea.setColumns(20);
        policyArea.setRows(5);
        jScrollPane2.setViewportView(policyArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(findPolicyText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1578, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(findPolicyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Find Policy", jPanel2);

        policyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(policyTable);

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 2293, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(updateButton))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Policies Information", jPanel4);

        policyTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(policyTable1);

        jLabel14.setText("Car Model");

        cmFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmFilterKeyReleased(evt);
            }
        });

        jLabel15.setText("Expiry Date");

        filterBDbutton.setText("Filter By Date");
        filterBDbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBDbuttonActionPerformed(evt);
            }
        });

        sort.setText("Sort by Name");
        sort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 2293, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(69, 69, 69)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(epFilter))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filterBDbutton)
                    .addComponent(sort))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sort))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(epFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterBDbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Filter Policy", jPanel5);

        jMenuBar2.add(jMenu4);

        LogoutOption.setText("Logout");
        LogoutOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutOptionMouseClicked(evt);
            }
        });
        jMenuBar2.add(LogoutOption);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutOptionMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        login.setVisible(true);
    }//GEN-LAST:event_LogoutOptionMouseClicked

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        idText.setText(user.getUserID() + "");
        nameText.setText(user.getName());
        usernameText.setText(user.getName());
        passText.setText(user.getPassword());
        streetNum.setText(user.getAddress().getStreetNum() + "");
        streetText.setText(user.getAddress().getStreet());
        suburbText.setText(user.getAddress().getSuburb());
        
        cityCombo.setModel(new DefaultComboBoxModel<String>(cities.toArray(new String[0])));
        cityCombo.setSelectedItem(user.getAddress().getCity());
        cityText.setText(user.getAddress().getCity());
        CarType[] carTypes = CarType.values();
        ctCombo1.removeAllItems();
        for(CarType ct: carTypes){
                
            ctCombo1.addItem(ct.toString().toUpperCase());
                
        }
        
        if(tppButton.isSelected()){

            lvlLabel.setVisible(false);
            lvlText.setVisible(false);
            commLabel.setText("Comment");

        }else{

            commLabel.setText("Driver Age");
            lvlLabel.setVisible(true);
            lvlText.setVisible(true);

        }
        
        policyTable.setComponentPopupMenu(policyTablePopUp);
//        policyTablePopUp.add(updateButton);
//        policyTablePopUp.add(deleteButton);
        fillTable();
        fillTable1();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void cityChoiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cityChoiceItemStateChanged
        // TODO add your handling code here:
        if(cityChoice.isSelected()){
            
            cityCombo.setEnabled(false);
            cityText.setEnabled(true);
            
        }else{
            
            cityCombo.setEnabled(true);
            cityText.setEnabled(false);
            
        }
    }//GEN-LAST:event_cityChoiceItemStateChanged

    private void addPolTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPolTextActionPerformed
        // TODO add your handling code here:
        try{

            String policyHoldName = polText1.getText();
            int policyID = Integer.parseInt(polID1.getText());
            String carModel = cmText1.getText();
            int manufacturingYear = Integer.parseInt(myText1.getText());
            double price = Double.parseDouble(pText1.getText());
            CarType carType = CarType.valueOf(ctCombo1.getSelectedItem().toString().toUpperCase());
            Car newCar = new Car(carModel, manufacturingYear, price, carType);
            int numberOfClaims = Integer.parseInt(nocText1.getText());
            int day = Integer.parseInt(dText.getText());
            int month = Integer.parseInt(mText.getText());
            int year = Integer.parseInt(yText.getText());
            MyDate newDate = new MyDate(year, month, day);
            InsurancePolicy ip;
            
            if(tppButton.isSelected()){
                
                String comment = cText.getText();
                ip = new ThirdPartyPolicy(policyHoldName, policyID, newCar, numberOfClaims, newDate, comment);
                
            }else{
                
                int driverAge = Integer.parseInt(cText.getText());
                int level = Integer.parseInt(lvlText.getText());
                ip = new ComprehensivePolicy(policyHoldName, policyID, newCar, numberOfClaims, newDate, driverAge, level);
                
            }
            
            if(user.addPolicy(ip, user.getName(), user.getPassword())){
                
                JOptionPane.showMessageDialog(this, "Policy has been added successfully!");
                polText1.setText("");
                polID1.setText("");
                cmText1.setText("");
                myText1.setText("");
                pText1.setText("");
                nocText1.setText("");
                dText.setText("");
                mText.setText("");
                yText.setText("");
                cText.setText("");
                lvlText.setText("");
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Policy has not been added successfully!");
                
            }

        }
             
        catch(PolicyException e){
            
            JOptionPane.showMessageDialog(this, "You have not entered the right pattern for a policy ID (for example: 3XXXXXX)");
            
        }
        
        catch(PolicyHolderNameException e){
            
            JOptionPane.showMessageDialog(this, "You have not entered the right pattern for a policy holder name (for example: John Wick)");
            
        }
        
        catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "A field may be empty or you have entered a string where it asks for an integer!");
             
        }
        
        
    }//GEN-LAST:event_addPolTextActionPerformed

    private void changeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDataActionPerformed
        // TODO add your handling code here:
        try{

            user.setName(nameText.getText());
            user.setPassword(passText.getText());
            user.getAddress().setStreetNum(Integer.parseInt(streetNum.getText()));
            user.getAddress().setStreet(streetText.getText());
            user.getAddress().setSuburb(suburbText.getText());

            if(cityChoice.isSelected()){

                user.getAddress().setCity(cityText.getText());
                cities.add(cityText.getText());
                cityCombo.setModel(new DefaultComboBoxModel<String>(cities.toArray(new String[0])));
                cityCombo.setSelectedItem(cityText.getText());

            }else{

                user.getAddress().setCity((String)cityCombo.getSelectedItem());
                cityText.setText(user.getAddress().getCity());

            }

        }catch(Exception e){

            JOptionPane.showMessageDialog(this, "You have entered a String. Please enter an integer!");

        }
    }//GEN-LAST:event_changeDataActionPerformed

    private void tppButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tppButtonStateChanged
        // TODO add your handling code here:
        if(tppButton.isSelected()){

            lvlLabel.setVisible(false);
            lvlText.setVisible(false);
            commLabel.setText("Comment");

        }else{

            commLabel.setText("Driver Age");
            lvlLabel.setVisible(true);
            lvlText.setVisible(true);

        }
    }//GEN-LAST:event_tppButtonStateChanged

    private void clearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearTextActionPerformed
        // TODO add your handling code here:
        polText1.setText("");
        polID1.setText("");
        cmText1.setText("");
        myText1.setText("");
        pText1.setText("");
        nocText1.setText("");
        dText.setText("");
        mText.setText("");
        yText.setText("");
        cText.setText("");
        lvlText.setText("");
    }//GEN-LAST:event_clearTextActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:
        try{
            
            InsurancePolicy ip = user.findPolicy(Integer.parseInt(findPolicyText.getText()), user.getName(), user.getPassword());
            if(ip != null){
                
                policyArea.append(ip.toString() + "\n");
                
            }else{
                
                policyArea.append("Policy with ID: " + findPolicyText.getText() + " could not be found! \n");
                
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "You have entered a string where an integer is required!");
            
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int ind = policyTable.getSelectedRow();
        
        if(ind >= 0){
            
            Object policyIDvalue = policyTable.getValueAt(ind, 1);
            
            if(policyIDvalue != null){
                
                int policyIDRetrived = Integer.parseInt(policyIDvalue.toString());

                HashMap<Integer, InsurancePolicy> policies = user.getPolicies();
                InsurancePolicy policyToRemove = user.getPolicies().get(policyIDRetrived);
                
                if(policyToRemove != null){
                    
                    policies.remove(policyIDRetrived);
                    fillTable();
                    
                }else{
                    
                    JOptionPane.showMessageDialog(this, "Cannot delete a policy that does not exist!");
                    
                }
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Cannot delete a policy that does not exist!");
                
            }
            
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int ind = policyTable.getSelectedRow();
        
        if(ind >= 0){
            
            Object policyIDvalue = policyTable.getValueAt(ind, 1);
            
            if(policyIDvalue != null){
                
                int policyIDRetrived = Integer.parseInt(policyIDvalue.toString());
                InsurancePolicy selectedPolicy = user.getPolicies().get(policyIDRetrived);
                
                UpdateUI updateUI = new UpdateUI(selectedPolicy, this);
                updateUI.setVisible(true);
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Policy selected is null");
                
            }
            
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cmFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmFilterKeyReleased
        // TODO add your handling code here:
        fillTable1();
    }//GEN-LAST:event_cmFilterKeyReleased

    private void filterBDbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBDbuttonActionPerformed
        // TODO add your handling code here:
        fillTable1();        
    }//GEN-LAST:event_filterBDbuttonActionPerformed

    private void sortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortActionPerformed
        // TODO add your handling code here:
        fillTable1();
    }//GEN-LAST:event_sortActionPerformed

    private void policyTablePopUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policyTablePopUpMousePressed
        // TODO add your handling code here:
        policyTablePopUp.show(this, evt.getX(), evt.getY());
    }//GEN-LAST:event_policyTablePopUpMousePressed

    private void DeletefromPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletefromPopUpActionPerformed
        // TODO add your handling code here:
        int ind = policyTable.getSelectedRow();
        
        if(ind >= 0){
            
            Object policyIDvalue = policyTable.getValueAt(ind, 1);
            
            if(policyIDvalue != null){
                
                int policyIDRetrived = Integer.parseInt(policyIDvalue.toString());

                HashMap<Integer, InsurancePolicy> policies = user.getPolicies();
                InsurancePolicy policyToRemove = user.getPolicies().get(policyIDRetrived);
                
                if(policyToRemove != null){
                    
                    policies.remove(policyIDRetrived);
                    fillTable();
                    
                }else{
                    
                    JOptionPane.showMessageDialog(this, "Cannot delete a policy that does not exist!");
                    
                }
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Cannot delete a policy that does not exist!");
                
            }
            
        }
    }//GEN-LAST:event_DeletefromPopUpActionPerformed

    private void UpdatefromPopUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatefromPopUpActionPerformed
        // TODO add your handling code here:
        int ind = policyTable.getSelectedRow();
        
        if(ind >= 0){
            
            Object policyIDvalue = policyTable.getValueAt(ind, 1);
            
            if(policyIDvalue != null){
                
                int policyIDRetrived = Integer.parseInt(policyIDvalue.toString());
                InsurancePolicy selectedPolicy = user.getPolicies().get(policyIDRetrived);
                
                UpdateUI updateUI = new UpdateUI(selectedPolicy, this);
                updateUI.setVisible(true);
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Policy selected is null");
                
            }
            
        }
    }//GEN-LAST:event_UpdatefromPopUpActionPerformed

    public void fillTable(){
        
        String[] header = {"Policy Holder Name","Policy ID","Car Model","Manufacturing Year","Price","Car Type","Number of Claims","Expiry Date","Comment","Driver Age","Level","Price for Policy"};
        DefaultTableModel model = new DefaultTableModel(header,0);
        policyTable.setModel(model);
        
        for(InsurancePolicy ip: user.getPolicies().values()){
            
            String[] row = new String[12];
            row[0] = ip.getPolicyHolderName();
            row[1] = ip.getID() + "";
            row[2] = ip.getCar().getModel();
            row[3] = ip.getCar().getManufacturingYear() + "";
            row[4] = ip.getCar().getPrice() + "";
            row[5] = ip.getCar().getType() + "";
            row[6] = ip.getNumberOfClaims() + "";
            row[7] = ip.getExpiryDate().toString();
            
            if(ip instanceof ThirdPartyPolicy){
                
                row[8] = ((ThirdPartyPolicy)ip).comments;
                row[9] = "NA";
                row[10] = "NA";
                
            }else{
                
                row[8] = "NA";
                row[9] = ((ComprehensivePolicy)ip).driverAge + "";
                row[10] = ((ComprehensivePolicy)ip).level + "";
                
            }
            
            row[11] = String.format("$%.2f", ip.calcPay(500));
            model.addRow(row);
            
        }
        
    }
    
    public void fillTable1(){
        
        ArrayList<InsurancePolicy> policyCopy = new ArrayList<>();
        for(InsurancePolicy policy1: user.getPolicies().values()){
            
            policyCopy.add(policy1);
            
        }
        
        try{
            
            if(!cmFilter.getText().isEmpty()){
                
                policyCopy = InsurancePolicy.filterByCarModel(policyCopy, cmFilter.getText());
                
            }
            
            if(!epFilter.getText().isEmpty()){
                
                String[] fields = epFilter.getText().split("/");
                int year = Integer.parseInt(fields[0]);
                int month = Integer.parseInt(fields[1]);
                int day = Integer.parseInt(fields[2]);
                MyDate aNewDate = new MyDate(year, month, day);
                policyCopy = InsurancePolicy.filterByExpiryDate(policyCopy, aNewDate);
                
            }
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(this, "JA KAM QR LALE");
            
        }
        
        if(sort.isSelected()){
            
            Collections.sort(policyCopy, new ComparisonByPolicyHolderName());
            
        }
        
        String[] header = {"Policy Holder Name","Policy ID","Car Model","Manufacturing Year","Price","Car Type","Number of Claims","Expiry Date","Comment","Driver Age","Level","Price for Policy"};
        DefaultTableModel model = new DefaultTableModel(header,0);
        policyTable1.setModel(model);
        
        for(InsurancePolicy ip: policyCopy){
            
            String[] row = new String[12];
            row[0] = ip.getPolicyHolderName();
            row[1] = ip.getID() + "";
            row[2] = ip.getCar().getModel();
            row[3] = ip.getCar().getManufacturingYear() + "";
            row[4] = ip.getCar().getPrice() + "";
            row[5] = ip.getCar().getType() + "";
            row[6] = ip.getNumberOfClaims() + "";
            row[7] = ip.getExpiryDate().toString();
            
            if(ip instanceof ThirdPartyPolicy){
                
                row[8] = ((ThirdPartyPolicy)ip).comments;
                row[9] = "NA";
                row[10] = "NA";
                
            }else{
                
                row[8] = "NA";
                row[9] = ((ComprehensivePolicy)ip).driverAge + "";
                row[10] = ((ComprehensivePolicy)ip).level + "";
                
            }
            
            row[11] = String.format("%.2f", ip.calcPay(500));
            model.addRow(row);
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main_UI(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserUI(user, login, cities).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DeletefromPopUp;
    private javax.swing.JMenu LogoutOption;
    private javax.swing.JMenuItem UpdatefromPopUp;
    private javax.swing.JButton addPolText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cText;
    private javax.swing.JButton changeData;
    private javax.swing.JCheckBox cityChoice;
    private javax.swing.JComboBox<String> cityCombo;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton clearText;
    private javax.swing.JTextField cmFilter;
    private javax.swing.JTextField cmText1;
    private javax.swing.JLabel commLabel;
    private javax.swing.JRadioButton cpButton;
    private javax.swing.JComboBox<String> ctCombo1;
    private javax.swing.JTextField dText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField epFilter;
    private javax.swing.JButton filterBDbutton;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField findPolicyText;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lvlLabel;
    private javax.swing.JTextField lvlText;
    private javax.swing.JTextField mText;
    private javax.swing.JTextField myText1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nocText1;
    private javax.swing.JTextField pText1;
    private javax.swing.JTextField passText;
    private javax.swing.JTextField polID1;
    private javax.swing.JTextField polText1;
    private javax.swing.JTextArea policyArea;
    private javax.swing.JTable policyTable;
    private javax.swing.JTable policyTable1;
    private javax.swing.JPopupMenu policyTablePopUp;
    private javax.swing.JCheckBox sort;
    private javax.swing.JTextField streetNum;
    private javax.swing.JTextField streetText;
    private javax.swing.JTextField suburbText;
    private javax.swing.JRadioButton tppButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField usernameText;
    private javax.swing.JTextField yText;
    // End of variables declaration//GEN-END:variables
}

class ComparisonByPolicyHolderName implements Comparator<InsurancePolicy> {
    
    @Override                                      
    public int compare(InsurancePolicy policy1, InsurancePolicy policy2){
            
        return policy1.getPolicyHolderName().compareTo(policy2.getPolicyHolderName());
            
    } 
    
}
